circuit:
    path: "/gpfs/bbp.cscs.ch/project/proj83/circuits/Bio_M/20200805/CircuitConfig"
    user.target: "/gpfs/bbp.cscs.ch/project/proj96/circuits/plastic_v1/user.target"
    target: "hex_O1"

extra_recipe_path: "/gpfs/bbp.cscs.ch/project/proj96/circuits/plastic_v1/recipe.csv"

out_sonata_fname: "/gpfs/bbp.cscs.ch/project/proj96/circuits/plastic_v1/edges.sonata"

sims_dir: "/gpfs/bbp.cscs.ch/project/proj96/home/ecker/plastyfire/helpersim"

fit_params:
    tau_effca_GB_GluSynapse: 314.3591654475
    gamma_d_GB_GluSynapse: 71.1227582108
    gamma_p_GB_GluSynapse: 225.7938528297
    a00: 1.0385210002
    a01: 1.5825822083
    a10: 1.2521176027
    a11: 2.8864347800
    a20: 4.5509160180
    a21: 1.1783764987
    a30: 3.3290522061
    a31: 3.9917748472
