circuit:
    path: "/gpfs/bbp.cscs.ch/project/proj83/circuits/Bio_M/20200805/CircuitConfig_NRRP_Update_2021_03_04_TC"
    user.target: "/gpfs/bbp.cscs.ch/project/proj96/circuits/plastic_v1/user.target"
    target: "hex_O1"

extra_recipe_path: "/gpfs/bbp.cscs.ch/project/proj96/circuits/plastic_v1/recipe.csv"

out_sonata_fname: "/gpfs/bbp.cscs.ch/project/proj96/circuits/plastic_v1/edges.sonata"

sims_dir: "/gpfs/bbp.cscs.ch/project/proj96/home/ecker/plastyfire/helpersim"

fit_params:
    tau_effca_GB_GluSynapse: 278.3177658387
    gamma_d_GB_GluSynapse: 101.5387594661
    gamma_p_GB_GluSynapse: 216.1841700668
    a00: 1.0018099627
    a01: 1.9535568661
    a10: 1.1593870631
    a11: 2.4827933785
    a20: 1.1267343377
    a21: 2.4559713296
    a30: 5.2356637311
    a31: 1.7822214534
