label: L5TTPC_L5TTPC
reference: Markram et al. 1997
seed: 19091997
npairs: 100
circuit:
    config: "/gpfs/bbp.cscs.ch/project/proj96/circuits/O1/circuit_config.json"
    node_set: "/gpfs/bbp.cscs.ch/project/proj96/circuits/O1/node_sets.json"
    target: "hex_O1Excitatory"
    node_pop: "S1nonbarrel_neurons"
    edge_pop: "S1nonbarrel_neurons__S1nonbarrel_neurons__chemical"
pregid_conf:
    mtype: ["L5_TPC:A", "L5_TPC:B"]
postgid_conf:
    mtype: ["L5_TPC:A", "L5_TPC:B"]
geom_cons:
    max_dist: [50., 50., 10.]  # [x, y, z] um
sims_dir: "/gpfs/bbp.cscs.ch/project/proj96/scratch/home/ecker/bcl-plastyfire/"
stimulus:
    freq: [40., 30., 20., 10., 5., 2.]  # Hz
    amp: "find"  # nA
    amp_min: 0.5
    amp_max: 3.0
    amp_lev: 10
    nspikes: 5
    dt: [5., 10., -10.]  # ms
    width: 3.0
    T: 4000  # ms
    offset: 1000  # ms
    nreps: 10
    C01_duration: 4  # min
    C02_duration: 4  # min
simulator:
    env: "/gpfs/bbp.cscs.ch/project/proj96/home/ecker/plastyfire/setupenv.sh"
    run: "/gpfs/bbp.cscs.ch/project/proj96/home/ecker/plastyfire/plastyfire/pairrunner.py"

