circuit:
    config: "/gpfs/bbp.cscs.ch/project/proj96/circuits/O1/circuit_config.json"
    node_set: "/gpfs/bbp.cscs.ch/project/proj96/circuits/O1/node_sets.json"
    target: "hex_O1Excitatory"
    node_pop: "S1nonbarrel_neurons"
    edge_pop: "S1nonbarrel_neurons__S1nonbarrel_neurons__chemical"
use_extra_recipe: 1
sims_dir: "/gpfs/bbp.cscs.ch/project/proj96/scratch/home/ecker/bcl-plastyfire/"
out_dir: "/gpfs/bbp.cscs.ch/project/proj96/circuits/plastic_v1/"
fit_params:
    tau_effca_GB_GluSynapse: 278.3177658387
    gamma_d_GB_GluSynapse: 101.5387594661
    gamma_p_GB_GluSynapse: 216.1841700668
    a00: 1.0018099627
    a01: 1.9535568661
    a10: 1.1593870631
    a11: 2.4827933785
    a20: 1.1267343377
    a21: 2.4559713296
    a30: 5.2356637311
    a31: 1.7822214534
simulator:
    env: "/gpfs/bbp.cscs.ch/project/proj96/home/ecker/plastyfire/setupenv.sh"
    run: "/gpfs/bbp.cscs.ch/project/proj96/home/ecker/plastyfire/plastyfire/thresholdfinder.py"